/* Select project located in 'Stafford', list project no, department no, name, of department, departments's manager name. */
CREATE VIEW Q1 AS
SELECT PNUMBER, DNUMBER, DNAME, FNAME AS MANAGER_NAME
FROM EMPLOYEE, DEPARTMENT, PROJECT
WHERE PLOCATION='STAFFORD'AND DNUM=DNUMBER AND MGRSSN=SSN


CREATE OR REPLACE VIEW Q2_2 AS
SELECT FNAME, LNAME, EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DATE) AS AGE, DNUMBER AS DNO
FROM DEPARTMENT, EMPLOYEE
WHERE DNUMBER=4 AND DNUMBER=DNO

SELECT * FROM (Q1 JOIN Q2_2 ON DNUMBER=DNO)
